version: '2'

services:
  app:
    image: 'wmsfernando/automated-healthcare-system:latest'
    build:
      context: .
    container_name: app
    ports:
      - "5050:5050"
    depends_on:
      - ahs-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ahs-db:5432/automated_health_system
      - SPRING_DATASOURCE_USERNAME=ahs_admin
      - SPRING_DATASOURCE_PASSWORD=Password12
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  ahs-db:
    image: 'postgres:13.1-alpine'
    container_name: ahs-db
    restart: unless-stopped
    environment:
      - POSTGRES_DB=automated_health_system
      - POSTGRES_USER=ahs_admin
      - POSTGRES_PASSWORD=Password12
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:

