name: Build and Deployment Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
jobs:
  build-and-deploy:
    runs-on: [ ubuntu-latest ]
    steps:
      - name: Checkout source
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Start PostgreSQL on Ubuntu
        run: |
          sudo systemctl start postgresql.service
          pg_isready

      - name: Create additional user
        run: |
          sudo -u postgres psql --command="CREATE USER ahs_admin PASSWORD 'Password12'" --command="\du"

      - name: Create additional database
        run: |
          sudo -u postgres createdb automated_health_system --owner=ahs_admin 
          PGPASSWORD=Password12 

      - name: Build Project
        run: mvn clean install

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: learnlo-backend
          path: '${{ github.workspace }}/target/*.jar'

      - name: Run Tests
        run: mvn test